-- MySQL Script generated by MySQL Workbench
-- Sun Mar  3 10:37:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jmdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jmdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jmdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `jmdb` ;

-- -----------------------------------------------------
-- Table `jmdb`.`casting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`casting` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`director` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`language` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `language` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `altTitle` VARCHAR(150) NULL DEFAULT NULL,
  `year` INT NULL DEFAULT NULL,
  `duration` INT NULL DEFAULT NULL,
  `cover` VARCHAR(150) NULL DEFAULT NULL,
  `trailer` VARCHAR(150) NULL DEFAULT NULL,
  `pitch` VARCHAR(500) NULL DEFAULT NULL,
  `story` VARCHAR(1000) NULL DEFAULT NULL,
  `location` VARCHAR(150) NULL DEFAULT NULL,
  `videoFormat` VARCHAR(10) NULL DEFAULT NULL,
  `comment` VARCHAR(500) NULL DEFAULT NULL,
  `videoSupport` VARCHAR(50) NULL DEFAULT NULL,
  `fileSize` INT NULL DEFAULT NULL,
  `idTheMovieDb` VARCHAR(10) NULL DEFAULT NULL,
  `idIMDb` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`movie_casting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`movie_casting` (
  `casting_id` INT NOT NULL,
  `movies_id` INT NOT NULL,
  INDEX `fk_movie_casting_casting1_idx` (`casting_id` ASC) VISIBLE,
  INDEX `fk_movie_casting_movies1_idx` (`movies_id` ASC) VISIBLE,
  CONSTRAINT `fk_movie_casting_casting1`
    FOREIGN KEY (`casting_id`)
    REFERENCES `jmdb`.`casting` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_casting_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `jmdb`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`movie_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`movie_country` (
  `movies_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  INDEX `fk_movie_country_movies1_idx` (`movies_id` ASC) VISIBLE,
  INDEX `fk_movie_country_country1_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_movie_country_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `jmdb`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_country_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `jmdb`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`movie_director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`movie_director` (
  `movies_id` INT NOT NULL,
  `director_id` INT NOT NULL,
  INDEX `fk_movie_director_movies1_idx` (`movies_id` ASC) VISIBLE,
  INDEX `fk_movie_director_director1_idx` (`director_id` ASC) VISIBLE,
  CONSTRAINT `fk_movie_director_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `jmdb`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_director_director1`
    FOREIGN KEY (`director_id`)
    REFERENCES `jmdb`.`director` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`movie_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`movie_genre` (
  `movies_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  INDEX `fk_movie_genre_movies_idx` (`movies_id` ASC) VISIBLE,
  INDEX `fk_movie_genre_genre1_idx` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `fk_movie_genre_movies`
    FOREIGN KEY (`movies_id`)
    REFERENCES `jmdb`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_genre_genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `jmdb`.`genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`movie_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`movie_language` (
  `movies_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  INDEX `fk_movie_language_movies1_idx` (`movies_id` ASC) VISIBLE,
  INDEX `fk_movie_language_language1_idx` (`language_id` ASC) VISIBLE,
  CONSTRAINT `fk_movie_language_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `jmdb`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_language_language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `jmdb`.`language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`compositor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`compositor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`movie_music`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`movie_music` (
  `movies_id` INT NOT NULL,
  `compositor_id` INT NOT NULL,
  INDEX `fk_movie_music_movies1_idx` (`movies_id` ASC) VISIBLE,
  INDEX `fk_movie_music_compositor1_idx` (`compositor_id` ASC) VISIBLE,
  CONSTRAINT `fk_movie_music_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `jmdb`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_music_compositor1`
    FOREIGN KEY (`compositor_id`)
    REFERENCES `jmdb`.`compositor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`screenwriter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`screenwriter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`movie_screenwriter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`movie_screenwriter` (
  `movies_id` INT NOT NULL,
  `screenwriter_id` INT NOT NULL,
  INDEX `fk_movie_screenwriter_movies1_idx` (`movies_id` ASC) VISIBLE,
  INDEX `fk_movie_screenwriter_screenwriter1_idx` (`screenwriter_id` ASC) VISIBLE,
  CONSTRAINT `fk_movie_screenwriter_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `jmdb`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_screenwriter_screenwriter1`
    FOREIGN KEY (`screenwriter_id`)
    REFERENCES `jmdb`.`screenwriter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`studio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`studio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`movie_studio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`movie_studio` (
  `studioId` INT NOT NULL AUTO_INCREMENT,
  `movies_id` INT NOT NULL,
  `studio_id` INT NOT NULL,
  PRIMARY KEY (`studioId`),
  INDEX `fk_movie_studio_movies1_idx` (`movies_id` ASC) VISIBLE,
  INDEX `fk_movie_studio_studio1_idx` (`studio_id` ASC) VISIBLE,
  CONSTRAINT `fk_movie_studio_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `jmdb`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_studio_studio1`
    FOREIGN KEY (`studio_id`)
    REFERENCES `jmdb`.`studio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jmdb`.`movie_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jmdb`.`movie_tag` (
  `tag_id` INT NOT NULL,
  `movies_id` INT NOT NULL,
  INDEX `fk_movie_tag_tag1_idx` (`tag_id` ASC) VISIBLE,
  INDEX `fk_movie_tag_movies1_idx` (`movies_id` ASC) VISIBLE,
  CONSTRAINT `fk_movie_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `jmdb`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_tag_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `jmdb`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
