-- MySQL Script generated by MySQL Workbench
-- Sat Jan 20 11:51:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema street_art_hunterz
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `street_art_hunterz` ;
-- -----------------------------------------------------
-- Schema street_art_hunterz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `street_art_hunterz` DEFAULT CHARACTER SET utf8mb3 ;
USE `street_art_hunterz` ;
-- -----------------------------------------------------
-- Table `street_art_hunterz`.`artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `street_art_hunterz`.`artist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;
-- -----------------------------------------------------
-- Table `street_art_hunterz`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `street_art_hunterz`.`location` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `image` TEXT NOT NULL,
  `postalcode` TEXT NOT NULL,
  `lat` DECIMAL(16, 14) NOT NULL,
  `lng` DECIMAL(15, 14) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;
-- -----------------------------------------------------
-- Table `street_art_hunterz`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `street_art_hunterz`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(20) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `registrationDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `score` INT DEFAULT '0',
  `admin` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;
-- -----------------------------------------------------
-- Table `street_art_hunterz`.`work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `street_art_hunterz`.`work` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `latitude` DECIMAL(16, 14) NOT NULL,
  `longitude` DECIMAL(15, 14) NOT NULL,
  `image` TEXT NOT NULL,
  `User_id` INT,
  `entry` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `isValidate` TINYINT NOT NULL,
  `location_id` INT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Work_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Work_location1_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_Work_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `street_art_hunterz`.`user` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_Work_location1`  -- Ajout de la clé étrangère
    FOREIGN KEY (`location_id`)
    REFERENCES `street_art_hunterz`.`location` (`id`) ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;
-- -----------------------------------------------------
-- Table `street_art_hunterz`.`artist_work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `street_art_hunterz`.`artist_work` (
  `Artist_id` INT NOT NULL,
  `Work_id` INT NOT NULL,
  PRIMARY KEY (`Artist_id`, `Work_id`),
  INDEX `fk_Artist_has_Work_Work1_idx` (`Work_id` ASC) VISIBLE,
  INDEX `fk_Artist_has_Work_Artist1_idx` (`Artist_id` ASC) VISIBLE,
  CONSTRAINT `fk_Artist_has_Work_Artist1`
    FOREIGN KEY (`Artist_id`)
    REFERENCES `street_art_hunterz`.`artist` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_Artist_has_Work_Work1`
    FOREIGN KEY (`Work_id`)
    REFERENCES `street_art_hunterz`.`work` (`id`) ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;